name: CI

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [staging, main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    uses: 0xPlayerOne/code-foundry/.github/workflows/ci.yml@v0.27.0
    with:
      runtime-repository: 0xPlayerOne/code-foundry
      runtime-ref: v0.27.0
      runner: ubuntu-latest
    secrets: inherit
